-- Whitelist small/mid-caps cotées UE/EEE, secteurs CPV ciblés (défense/sécurité 35,
-- médical/biotech 33, logiciel/IT 72, énergie verte/infra 09330000).
-- Focus UE + EEE (Norvège incluse) : ces sociétés soumissionnent EN DIRECT aux
-- marchés publics UE. Suisse retirée (hors EEE -> gagne via filiales UE dont le nom
-- diffère de la mère cotée -> ne matche pas). UK gardé mais affaibli (Brexit).
-- market_cap / annual_revenue_eur NULL -> yfinance remplit au match (filtre 100 M–2 Md).
-- ⚠️ La mère cotée peut soumissionner via une filiale : le fuzzy match (0.87) + le LLM
-- rattrapent les variantes ; les small-caps mono-entité matchent le mieux.

INSERT OR IGNORE INTO small_caps_whitelist (company_name_cleaned, ticker, exchange) VALUES
-- === Défense / Sécurité (CPV 35) ===
('exail technologies',        'EXA.PA',    'Euronext Paris'),
('theon international',        'THEON.AS',  'Euronext Amsterdam'),
('exosens',                   'EXENS.PA',  'Euronext Paris'),
('mildef',                    'MILDEF.ST', 'Nasdaq Stockholm'),
('hensoldt',                  'HAG.DE',    'Xetra'),
('vaisala',                   'VAIAS.HE',  'Nasdaq Helsinki'),
('chemring',                  'CHG.L',     'LSE'),
('cohort',                    'CHRT.L',    'LSE AIM'),
('avon protection',           'AVON.L',    'LSE'),
('qinetiq',                   'QQ.L',      'LSE'),

-- === Médical / Biotech / Diagnostic (CPV 33) ===
('elekta',                    'EKTA-B.ST', 'Nasdaq Stockholm'),
('ambu',                      'AMBU-B.CO', 'Nasdaq Copenhagen'),
('revenio',                   'REG1V.HE',  'Nasdaq Helsinki'),
('surgical science',          'SUS.ST',    'Nasdaq Stockholm'),
('vitrolife',                 'VITR.ST',   'Nasdaq Stockholm'),
('biotage',                   'BIOT.ST',   'Nasdaq Stockholm'),
('cellavision',               'CEVI.ST',   'Nasdaq Stockholm'),
('boule diagnostics',         'BOUL.ST',   'Nasdaq Stockholm'),
('xvivo perfusion',           'XVIVO.ST',  'Nasdaq Stockholm'),
('medistim',                  'MEDI.OL',   'Oslo Bors'),
('bavarian nordic',           'BAVA.CO',   'Nasdaq Copenhagen'),
('valneva',                   'VLA.PA',    'Euronext Paris'),
('innate pharma',             'IPH.PA',    'Euronext Paris'),
('biosynex',                  'ALBIO.PA',  'Euronext Paris'),
('nyxoah',                    'NYXH.BR',   'Euronext Brussels'),
('eckert ziegler',            'EUZ.DE',    'Xetra'),
('stratec',                   'SBS.DE',    'Xetra'),
('draegerwerk',               'DRW3.DE',   'Xetra'),
('pharmanutra',               'PHN.MI',    'Borsa Italiana'),
('bico',                      'BICO.ST',   'Nasdaq Stockholm'),
('sectra',                    'SECT-B.ST', 'Nasdaq Stockholm'),
('advanced medical solutions', 'AMS.L',    'LSE AIM'),
('tristel',                   'TSTL.L',    'LSE AIM'),
('ekf diagnostics',           'EKF.L',     'LSE AIM'),

-- === Logiciel / IT (CPV 72), fournisseurs secteur public ===
('netcompany',                'NETC.CO',   'Nasdaq Copenhagen'),
('addnode',                   'ANOD-B.ST', 'Nasdaq Stockholm'),
('knowit',                    'KNOW.ST',   'Nasdaq Stockholm'),
('formpipe software',         'FPIP.ST',   'Nasdaq Stockholm'),
('vitec software',            'VIT-B.ST',  'Nasdaq Stockholm'),
('enea',                      'ENEA.ST',   'Nasdaq Stockholm'),
('lime technologies',         'LIME.ST',   'Nasdaq Stockholm'),
('gofore',                    'GOFORE.HE', 'Nasdaq Helsinki'),
('siili solutions',           'SIILI.HE',  'Nasdaq Helsinki'),
('innofactor',                'IFA1V.HE',  'Nasdaq Helsinki'),
('digia',                     'DIGIA.HE',  'Nasdaq Helsinki'),
('init',                      'IXX.DE',    'Xetra'),
('gft technologies',          'GFT.DE',    'Xetra'),
('cancom',                    'COK.DE',    'Xetra'),
('atoss software',            'AOF.DE',    'Xetra'),
('kontron',                   'KTN.DE',    'Xetra'),
('nagarro',                   'NA9.DE',    'Xetra'),
('snp schneider neureither',  'SHF.DE',    'Xetra'),
('wallix',                    'ALLIX.PA',  'Euronext Paris'),
('esker',                     'ALESK.PA',  'Euronext Paris'),
('neurones',                  'NRO.PA',    'Euronext Paris'),
('aubay',                     'AUB.PA',    'Euronext Paris'),
('infotel',                   'INF.PA',    'Euronext Paris'),
('sii',                       'SII.PA',    'Euronext Paris'),
('sword',                     'SWP.PA',    'Euronext Paris'),
('kainos',                    'KNOS.L',    'LSE'),
('bytes technology',          'BYIT.L',    'LSE'),

-- === Énergie verte / Infra (CPV 09330000 & connexes) ===
('scatec',                    'SCATC.OL',  'Oslo Bors'),
('nel',                       'NEL.OL',    'Oslo Bors'),
('cadeler',                   'CADLR.OL',  'Oslo Bors'),
('voltalia',                  'VLTSA.PA',  'Euronext Paris'),
('grenergy',                  'GRE.MC',    'BME Madrid'),
('solaria',                   'SLR.MC',    'BME Madrid'),
('alfen',                     'ALFEN.AS',  'Euronext Amsterdam'),
('sfc energy',                'F3C.DE',    'Xetra'),
('sma solar technology',      'S92.DE',    'Xetra'),
('energiekontor',             'EKT.DE',    'Xetra'),
('2g energy',                 '2GB.DE',    'Xetra'),
('pne',                       'PNE3.DE',   'Xetra'),
('verbio',                    'VBK.DE',    'Xetra'),
('powercell',                 'PCELL.ST',  'Nasdaq Stockholm'),
('ceres power',               'CWR.L',     'LSE'),
('itm power',                 'ITM.L',     'LSE AIM'),
('7c solarparken',            'HRPK.DE',   'Xetra');
